<!DOCTYPE html>
<html>
<body>

<div align="center">
<h3>Prepared by Shaig E.Kazimov</h3>
    
<h1>Python exercises</h1>

<h3>Follow Me on - <a href="https://www.linkedin.com/in/shaig-kazimov/">LinkedIn</a>&nbsp;

</div>
</body>
</html>

# Variables

Create a variable with name "x" and a value of 10. Execute.

In [1]:
x=10

Tell the computer to show you the value of that variable.

In [2]:
print(x)

10


Can you think of a second way to obtain the same result?

In [4]:
x

10

On the same line, create four new variables: a,b,c, and d, that are equal to 10, 20, 30, and 40, respectively.

In [5]:
a,b,c,d=(10,20,30,40)

Tell the computer to show you the value corresponding to the variable "b".

In [6]:
print(b)

20


Do the same for "d".

In [7]:
print(d)

40


_________________________________

# Numbers and Boolean Values

Create a variable equal to "True".

In [8]:
r=True

Check its type.

In [9]:
type(r)

bool

Create a variable equal to 99.

In [10]:
w=99

Check its type.

In [11]:
type(w)

int

Check the type of the value 0.99.

In [13]:
t=0.99
type(t)

float

Turn 99 into a float.

In [19]:
w=float(w)
type(w)

float

Turn 0.99 into an integer. What value did you get?

In [21]:
t=int(t)
type(t)

int

_________________________________

# Strings

Assign the value of 100 to the variable "m".

In [382]:
m=100

With the help of the variable "m", write one line of code where the output after executuion would be 100 days.

Hint: You could provide four answers to this question!

In [383]:
print(str(m) + " days")


100 days


In [384]:
print(f"{m} days")


100 days


In [385]:
print("{} days".format(m))


100 days


Produce an output equal to It's cool, isn't it?

In [23]:
y="It's cool, isn't it?"
print(y)

It's cool, isn't it?


Fix the string below.

In [24]:
"'Don't be shy"

"'Don't be shy"

Produce an output equal to Click "OK".

In [29]:
s='Click \"OK"'
print(s)

Click "OK"


Include a plus sign in your line of code to produce 'Big Houses'.

In [31]:
print('Big'+' '+'Houses')

Big Houses


Include a trailing comma in your line of code to produce Big Houses.

In [32]:
print('Big','Houses')

Big Houses


__________________

# Arithmetic operators

Combine 15 and 23.

In [33]:
15+23

38

Subtract 50 from 26.

In [34]:
50-26

24

Divide 20 by 4.

In [35]:
20/4

5.0

Divide 22 by 4.

In [40]:
22/4

5.5

Obtain the remainder of the division of 22 by 4.

In [41]:
22%4

2

Divide the float 22 by 4.

In [42]:
a=float(22)

In [43]:
a/4

5.5

Multiply 6 by 8.

In [44]:
6*8

48

Raise 15 to the power of 2.

In [45]:
15**2

225

_____________________

# The double-equality sign

Demonstrate that 100 is not equal to 98.

In [48]:
100==98

False

__________________________

# Reassign Values

Assign the value of 14 to a variable p.

In [49]:
p=14

Calculate p + 10.

In [50]:
p+10

24

Now, assign 30 to the variable p.

In [51]:
p=30

Calculate p + 10.

In [52]:
p+10

40

Observe how the value of p is always the last one you have assigned.

In [53]:
print(p)

30


___________________

# Indexing Elements

Extract the letter 'B' from "Bingo!".

In [58]:
a="Bingo!"

In [59]:
a[0]

'B'

Extract the letter "u" from "Constitution".

In [60]:
b='Constitution'

In [61]:
b[7]

'u'

________________

# Structure Your Code with Indentation

Use indentation properly to print the result of the function with an argument of 3.

In [65]:
    def ten(x):
        x = 10
        return x
print (ten(3))

10


___________________

# Comparison Operators

Verify that 25 is smaller than 30.

In [66]:
25<30

True

Verify that 5 multiplied by 3 is less than or equal to 5 to the power of 3.

In [69]:
5*3 <=5**3

True

Verify that 100 is equal to 10 square.

In [70]:
100==10**2

True

Verify that 53 is not equal to 46.

In [73]:
53==46

False

___________________

# Logical and Identity Operators 

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

Check whether the following code is True or False.

False or not True and not False

In [76]:
(False or not True) and not False

False

True and not False and True or not False

In [75]:
(True and not False) and not False

True

True or False and False

In [78]:
True or False and False

True

False and True or False

In [81]:
False and True or False

False

Using an identity operator, verify that 10 is not the same as 12.

In [83]:
10 != 12

True

Using an identity operator, verify that 50 is the same as 50.

In [84]:
50==50

True

____________________

# Introduction to the IF statement

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

Create a two-line code that prints "The condition has been satisfied" if 5 is greater than 2.

In [86]:
if 5>2:
    print('The condition has been satisfied')

The condition has been satisfied


Assign 10 to the variable x and 25 to the variable y. In the same cell, create 2 conditional statements. Let the first one print "Both conditions are correct" if x is greater then 3 and y is greater than 13. Let the second one print "At least one of the conditions is false" if x is less than or equal to 3 and y is less than or equal to 13. Change the values assigned to x and y and re-run the cell to verify your code still works.

In [93]:
x=22 ;y=55
if x>3 and y>13:
    print('Both conditions are correct')
elif x<=3 and y<= 13:
    print('At least one of the conditions is false')

Both conditions are correct


____________________________

# Add an ELSE Statement

Let x represent the number of orders received during a certain day. Assign 102 to x. Create a program that prints "A busy day" if x is greater than 100, and "A calm day" otherwise. Change x to 97 to verify your code works properly.

In [101]:
x=102
def orders(x):
    if x>100 :
        print('A busy day')
    else:
        print('A calm day')

orders(5)    

A calm day


_________________

# Else if, for Brief - ELIF

Assign 200 to x. Create the following piece of code: If x > 200, print out "Big"; If x > 100 and x <= 200, print out "Average"; and If x <= 100, print out "Small". Use the If, Elif, and Else keywords in your code.

In [112]:
x=20
if x>200:
    print('Big')
elif x>100 and x<=200:
    print('Average')
elif x<= 100:
    print('Small')

Small


Change the initial value of x to see how your output will vary.

In [113]:
x=50
if x>200:
    print('Big')
elif x>100 and x<=200:
    print('Average')
elif x>=0 and x<=100:
    print('Small')
elif x<0:
    print('Negative')
    

Small


Keep the first two conditions of the previous code. Add a new ELIF statement, so that, eventually, the program prints "Small" if x >= 0 and x <= 100, and "Negative" if x < 0. Let x carry the value of 50 and then of -50 to check if your code is correct.

In [114]:
x=-50
if x>200:
    print('Big')
elif x>100 and x<=200:
    print('Average')
elif x>=0 and x<=100:
    print('Small')
elif x<0:
    print('Negative')

Negative


_____________________

# Creating a Function with a Parameter

Define a function that returns a value equal to its argument multiplied by 2.

In [116]:
def multiple(x):
    print(x*2)

In [117]:
multiple(3)

6


Define a funciton that returns a float value equal to its argument divided by 2.

In [118]:
def devide(x):
    print (float(x)/2)

In [119]:
devide(13)

6.5


_________________

# Another Way to Define a Function

Define a function that states the value of the argument accompanied by the phrase "Raised to the power of 2:" and returns a value equal to its argument raised to the power of 2. This time, use a new variable, called "result", in the body of the Function. Call the function with some argument to verify it works properly.

Hint: Your knowledge about stating multiple elements on a line can be of great help in solving this exercise!

In [150]:
def justtry (X):
    result=X**2
    print('Raised to the power of 2:', X)
    return result

In [153]:
yekun=justtry(5)
print(yekun)

Raised to the power of 2: 5
25


_____________

# Using a Function in Another Function

Define a function that adds 5 to the parameter. Then, define another function that will multiply the newly obtained number by 3. Verify your code was correct by calling the second function with an argument of 5. Was your output equal to 30?

In [162]:
def add(x):
    print(x+5)
    return (x+5)*3

In [163]:
add(5)

10


30

____________________

# Combining Conditional Statements and Functions

Define a function, called compare_the_two(), with two arguments. If the first one is greater than the second one, let it print "Greater". If the second one is greater, it should print "Less". Let it print "Equal" if the two values are the same number.

In [164]:
def compare_the_two(x,y):
    if x>y:
        print('greater')
    elif y>x:
        print('less')
    else:
        print('equal')

In [165]:
compare_the_two(1,5)

less


__________________

# Notable Built-In Functions in Python

Obtain the maximum number among the values 25, 65, 890, and 15.

In [166]:
print(max(25,65,890,15))

890


Obtain the minimum number among the values 25, 65, 890, and 15.

In [167]:
print(min(25,65,890,15))

15


Find the absolute value of -100

In [168]:
print(abs(-100))

100


Round the value of 55.5. Did you obtain 56.0?

In [176]:
print(round(55.5))


56


Round 35.56789 to the third digit.

In [181]:
print(round(35.56789,3))

35.568


Find the sum of all elements in the provided list, called "Numbers".

In [182]:
Numbers = [1, 5, 64, 24.5]

In [183]:
sum(Numbers)

94.5

Use a built-in function to raise 10 to the power of 3.

In [188]:
print(pow(10,3))

1000


How many characters are there in the word "Elephant"?

In [189]:
len('Elephant')

8

Create a function, called "distance_from_zero", that returns the absolute value of a provided single argument and prints a statement "Not Possible" if the argument provided is not a number. Call the funtion with the values of -10 and "cat" to verify it works correctly.

In [194]:
def distance_from_zero(x):
    if isinstance(x,(int,float)): 
        return abs(x)
    else:
        print("Not Possible")

In [191]:
distance_from_zero(-10)

10

In [193]:
distance_from_zero('cat')

Not Pssible


____________________

# Lists

Create a list, called "Numbers". Let it contain the numbers 10, 25, 40, and 50.

In [211]:
Numbers=[10,25,40,50]

Print the second element from the list.

In [212]:
Numbers[2]

40

Print the 0th element.

In [213]:
Numbers[0]

10

Print the third-to-last element using a minus sign in the brackets.

In [214]:
Numbers[-1]

50

Substitute the number 10 with the number 15.

In [215]:
Numbers[0]=15
Numbers

[15, 25, 40, 50]

Delete the number 25 from the Numbers list.

In [216]:
Numbers.remove(25)

______________

# Help Yourself with Methods

Append the number 100 to the Numbers list.

In [217]:
Numbers = [15, 40, 50]

In [218]:
Numbers.append(100)

With the help of the "extend method", add the numbers 115 an 140 to the list.

In [219]:
Numbers.extend([115,140])

Print a statement, saying "The fourth element of the Numbers list is:" and then designate the value of the fourth element. Use a trailing comma.

In [220]:
Numbers

[15, 40, 50, 100, 115, 140]

How many elements are there in the Numbers list?

In [221]:
len(Numbers)

6

________________

# List Slicing

In [227]:
Numbers = Numbers = [15, 40, 50, 100, 115, 140]

Using list slicing, obtain the numbers 100 and 115.

In [229]:
print(Numbers[3:5])

[100, 115]


Using slicing, extract the first four elements from the list.

In [231]:
print(Numbers[0:4])

[15, 40, 50, 100]


Using slicing, extract all the elements from the list from the 3rd position onwards.

In [232]:
print(Numbers[2:])

[50, 100, 115, 140]


Using slicing, extract the last 4 elements from the list.

In [239]:
print(Numbers[-4:])

[50, 100, 115, 140]


Which is the position of the value 15?

In [240]:
Numbers.index(15)

0

Create a list, called "Two_Numbers". Let its elements be the values 1 and 2. Then, create a new one, named "All_Numbers", that will containt both the "Numbers" and the "Two_Numbers" lists.

In [250]:
Two_Numbers=[1,2]
All_Numbers=[Numbers,Two_Numbers]
print(All_Numbers)

[[15, 40, 50, 100, 115, 140], [1, 2]]


[15, 40, 50, 100, 115, 140]

Sort all the numbers in the "Numbers" list from the largest to the smallest.

In [258]:
Numbers.sort(reverse=True)
print(Numbers)

[140, 115, 100, 50, 40, 15]


__________________

# Tuples

Create a tuple, called "Cars", with elements "BMW", "Dodge", and "Ford".

In [259]:
Cars=('BMW','Dodge','Ford')

Access the second element of this tuple.

In [260]:
Cars[1]

'Dodge'

Call a method that would allow you to extract the provided name and age separately. Then print the "name" and "age" values to see if you worked correctly.

In [262]:
name, age = 'Peter,24'

ValueError: too many values to unpack (expected 2)

In [265]:
name,age=('Peter',24)
print(name,age)

Peter 24


Create a function that takes as arguments the two values of a rectangle and then returns the Area and the Perimeter of the rectangle. Call the function with arguments 2 and 10 to verify it worked correctly.

In [272]:
def rectangle(x,y):
    print('Area is:', x*y,'Perimeter is:', 2*(x+y))

rectangle(2,10)

Area is: 20 Perimeter is: 24


________________________

# Dictionaries

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

This is the menu of a close-by restaurant:

In [273]:
Menu = {'meal_1':'Spaghetti', 'meal_2':'Fries', 'meal_3':'Hamburger', 'meal_4':'Lasagna'}

What is the second meal in the list?

In [276]:
Menu['meal_2']

'Fries'

Add a new meal - "Soup".

In [277]:
Menu['meal_5']='Soup'

Replace the Hamburger with a Cheeseburger.

In [279]:
Menu['meal_3']='Cheeseburger'

Attach the Desserts list in the form of a sixth meal.

In [15]:
Dessert = ['Pancakes', 'Ice-cream', 'Tiramisu']

In [280]:
Menu['Desserts']=['Pancakes', 'Ice-cream', 'Tiramisu']

Create a new dictionary that contains the first five meals as keys and assign the following five values as prices (in dollars): 10, 5, 8, 12, 5. Start by Price_list = {}.

Use the .get() method to check the price of the Spaghetti.

In [309]:
Price_list={}
Price_list['Spagetti']=10
Price_list['Fries']=5
Price_list['Cheeseburger']=8
Price_list['Lasanga']=12
Price_list['Soup']=5
spagetti_price=Price_list.get('Spagetti')
print(spagetti_price)

10


_____________________

# For Loops

Create a For loop that prints every digit on a new line.

In [310]:
digits = [0,1,2,3,4,5,6,7,8,9]

In [315]:
for i in digits:
    print(i)

0
1
2
3
4
5
6
7
8
9


Adjust the code, so the digits are all printed on the same line.

In [316]:
for i in digits:
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 

________________

# While Loops and Incrementing

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

Create a while loop that will print all odd numbers from 0 to 30 on the same row.

Hint: There are two ways in which you can create the odd values!

In [329]:
num=0
while num<=30:
    if num%2!=0:
        print(num,end=' ')
    num+=1

1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 

____________

# Create Lists with the range() Function

Use the range() function to create a list with all numbers from 1 to 10.

In [333]:
for i in range(1,10):
    print(i,end=' ')

1 2 3 4 5 6 7 8 9 

Use the range() function to create a list with all numbers from 0 to 19.

In [334]:
for i in range(0,19):
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 

Use the range function to create a list with all even numbers from 0 to 30 included.

In [340]:
for i in range(0,31):
    if i%2==0:
        print(i,end=' ')

0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 

_______________________

# Use Conditional Statements and Loops Together

Create a For loop that will print all the variables from a given list multiplied by 2. Let the list contain all numbers from 1 to 10. Create it with the help of the range() function.

In [341]:
for i in range(1,10):
    if i%2==0:
        print(i,end=' ')

2 4 6 8 

Create a little program that runs a loop over all values from 1 to 30. Let it print all Odd numbers, and in the place of the even numbers, it should print "Even". Help yourself with the range() function to solve this exercise.

In [344]:
for i in range(1,30):
    if i%2!=0:
        print("odd number",end=' ')
    else:
        print('Even',end=' ')
        

odd number Even odd number Even odd number Even odd number Even odd number Even odd number Even odd number Even odd number Even odd number Even odd number Even odd number Even odd number Even odd number Even odd number Even odd number 

You have the following list of numbers. Iterate over this list, printing out each list value multiplied by 10. Find two solutions of this problem.

In [351]:
n = [1,2,3,4,5,6]

In [352]:
for i in n:
    print(10*i)

10
20
30
40
50
60


In [357]:
i = 0
while i < len(n):
    print(n[i] * 10)
    i += 1


10
20
30
40
50
60


_________________

# All in - Conditional Statements, Functions, and Loops

You are provided with the 'nums' list. Complete the code in the cell that follows. Use a while loop to count the number of values lower than 20. You might prefer using the x[item] structure for indicating the value of an element from the list.

In [359]:
nums = [1,12,24,31,51,70,100]

In [367]:
for i in nums:
    if i<20:
        print(i)

1
12


____________

# Iterating over Dictionaries

In this exercise you will use the same dictionaries as the ones we used in the lesson - "prices" and "quantity". This time, don't just calculate all the money Jan spent. Calculate how much she spent on products with a price of 5 dollars or more.

In [374]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

In [375]:
for item in prices:
    if prices[item]>=5:
        money_spent+=prices[item]*quantity[item]
print(money_spent)

50


And how much did Jan spent on products that cost less than 5 dollars?

In [379]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

In [380]:
for i in prices:
    if prices[i]<5:
        money_spent+=prices[i]*quantity[i]
print(money_spent)

24
